# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07af5345ca2829fffa8d9c20390b854b9ecfaa8a820e93726e606911ed060687eec0885cc360d3b64666dab7c63bdb3f811249aad184597ff2a5b5c36e02b86b

test:
  secret_key_base: 0da9f19d3db0de54401589828a597331c1d740cc5b4e630d417ba34c1920ee82d95103aae98f755351d421cf0e62f1191fcd72661efe1813b82418672122a0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
